// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://pqrcdqoavblqhprpdnno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxcmNkcW9hdmJscWhwcnBkbm5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU5OTQ4MDgsImV4cCI6MjA4MTU3MDgwOH0.4W0QuKIoSq443AtJ7EalCKTaKKHXGvs2jo6yKChMoro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);